// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import LoadingProgressController from "./loading_progress_controller"
application.register("loading-progress", LoadingProgressController)

import SettingsMenuController from "./settings_menu_controller"
application.register("settings-menu", SettingsMenuController)

import RoutingDashboardController from "./routing_dashboard_controller"
application.register("routing-dashboard", RoutingDashboardController)

import ActivityFilterController from "./activity_filter_controller"
application.register("activity-filter", ActivityFilterController)
