// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import KanbanController from "./kanban_controller"
import DrawerController from "./drawer_controller"
import DraggableController from "./draggable_controller"
import LoadingProgressController from "./loading_progress_controller"

application.register("hello", HelloController)
application.register("kanban", KanbanController)
application.register("drawer", DrawerController)
application.register("draggable", DraggableController)
application.register("loading-progress", LoadingProgressController)
